# Generated by Django 2.2 on 2019-05-04 17:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_measurement.models
import measurement.measures.mass


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('contact_number', models.IntegerField()),
                ('profile_picture', models.ImageField(upload_to='images/')),
                ('Car_details', models.CharField(max_length=100)),
                ('Car_models_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='types_of_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='delivery_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_location', models.CharField(max_length=100)),
                ('from_location', models.CharField(max_length=100)),
                ('weight', django_measurement.models.MeasurementField(measurement=measurement.measures.mass.Mass)),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(upload_to='images/')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.types_of_product')),
            ],
        ),
    ]
